sudo: required
services:
  - docker

before_install:
  - docker build -t sandeep2995/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sandeep2995/react-test npm test -- --coverage

after_success:
  - docker build -t sandeep2995/multi-client ./client
  - docker build -t sandeep2995/multi-nginx ./nginx
  - docker build -t sandeep2995/multi-server ./server
  - docker build -t sandeep2995/multi-worker ./worker