sudo: required
services:
  - docker

before_install: # build the docker container using development setup
  - docker build -t sandeep2995/react-test -f ./client/Dockerfile.dev ./client

script: # test using development container setup
  # - docker run sandeep2995/react-test npm test -- --coverage
  - docker run -e CI=true sandeep2995/react-test npm test

after_success:
  # build the production ready docker images
  - docker build -t sandeep2995/multi-client ./client
  - docker build -t sandeep2995/multi-nginx ./nginx
  - docker build -t sandeep2995/multi-server ./server
  - docker build -t sandeep2995/multi-worker ./worker
  # login into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the built docker images into docker hub
  - docker push sandeep2995/multi-client
  - docker push sandeep2995/multi-nginx
  - docker push sandeep2995/multi-server
  - docker push sandeep2995/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-eu-central-1-403839203164
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
